### ISSUE TITLE
Add olm test libs for Windows/Mac/Linux

### ISSUE THREAD

**Issue by oncecrossover** [brevilo/jolm#16]
Add olm test libs to run JUnit tests quickly, do you think this is a good suggestion?

![image](https://user-images.githubusercontent.com/43728891/145963838-6441a185-2e61-422f-bd81-10f065bb38f7.png)

**Comment by oncecrossover** [comment]
Hey @brevilo，your efforts of fixing these bugs are greatly appreciated. Respecting your work of jolm, we’d like to sponsor somehow. Please kindly let’s know how.

**Comment by brevilo** [comment]
Let's discuss the sponsoring topic in #17 as it's completely independent of this one. Thanks.

**Comment by brevilo** [comment]
What exactly do you mean by adding "olm test libs" and what's the goal you want to achieve?

FYI, unit tests are already run automatically using GitHub's CI workflows (on push and for PRs). Granted, eventually it might be a good idea to run those unit tests on other platforms than just Linux (see #18).

If your question is about including or building upstream `libolm` as part of the jOlm installation or its unit test setup, then I can say that I considered that (see last point of the [status report](https://github.com/brevilo/jolm#status)) earlier. However, thinking a bit more about it, I don't see this as a useful feature anymore. The reason is that no one should trust me (or jOlm) to safely and securely provide the upstream `libolm` library. It's very important that users/developers get their copy of `libolm` from their preferred secure, trusted, standard software source since it's *the* central component for all Matrix E2EE features. That means users should either get the sources directly from upstream and compile them themselves or use binary packages provided by their preferred distribution channel (typically via a package manager like `apt`, `yum`, `homebrew`). If we agree on this then it doesn't make much sense to have them test against our own copies of `libolm` by shipping those with jOlm. Developers ought to run the tests against whatever they have installed on their concrete system since that's what jOlm will call and thus depend upon after all.

Cheers

**Comment by oncecrossover** [comment]
I see, please forget this ticket.
